Repository 100-hours-a-week/21-iceT-be, pull requests merged in 2025-05, with the labels that each got.

#7 [Feat] 카카오 OAuth를 통한 로그인 및 최초 사용자 등록 기능 구현 (#5)
  .idea/dataSources/b53a4fef-5b2d-4b59-9404-b62a8acb23ae.xml
  .idea/modules.xml
  .idea/modules/Koco.main.iml
  .idea/workspace.xml
  Koco/build.gradle
  Koco/src/main/java/icet/koco/KocoApplication.java
  Koco/src/main/java/icet/koco/auth/controller/AuthController.java
  Koco/src/main/java/icet/koco/auth/dto/AuthResponse.java
  Koco/src/main/java/icet/koco/auth/dto/KakaoCallbackRequest.java
  Koco/src/main/java/icet/koco/auth/dto/KakaoTokenResponse.java
  Koco/src/main/java/icet/koco/auth/dto/KakaoUserResponse.java
  Koco/src/main/java/icet/koco/auth/dto/LogoutResponse.java
  Koco/src/main/java/icet/koco/auth/dto/RefreshRequest.java
  Koco/src/main/java/icet/koco/auth/dto/RefreshResponse.java
  Koco/src/main/java/icet/koco/auth/repository/OAuthRepository.java
  Koco/src/main/java/icet/koco/auth/service/AuthService.java
  Koco/src/main/java/icet/koco/auth/service/KakaoOAuthClient.java
  Koco/src/main/java/icet/koco/auth/service/LogoutService.java
  Koco/src/main/java/icet/koco/config/SecurityConfig.java
  Koco/src/main/java/icet/koco/global/dto/ErrorResponse.java
  Koco/src/main/java/icet/koco/global/exception/ForbiddenException.java
  Koco/src/main/java/icet/koco/global/exception/GlobalExceptionHandler.java
  Koco/src/main/java/icet/koco/global/exception/ResourceNotFoundException.java
  Koco/src/main/java/icet/koco/global/exception/UnauthorizedException.java
  Koco/src/main/java/icet/koco/problemSet/entity/Solution.java
  Koco/src/main/java/icet/koco/user/repository/UserRepository.java
  Koco/src/main/java/icet/koco/util/JwtTokenProvider.java
  Koco/src/main/resources/application.properties
Labels: ✨feature, BE

#17 [Feat] 문제집 설문 응답 기능 구현 (#9)
  .idea/workspace.xml
  Koco/src/main/java/icet/koco/problemSet/controller/SurveyController.java
  Koco/src/main/java/icet/koco/problemSet/dto/ProblemSetSurveyRequestDto.java
  Koco/src/main/java/icet/koco/problemSet/dto/ProblemSurveyRequestDto.java
  Koco/src/main/java/icet/koco/problemSet/dto/SurveyResponseDto.java
  Koco/src/main/java/icet/koco/problemSet/repository/ProblemSetProblemRepository.java
  Koco/src/main/java/icet/koco/problemSet/service/ProblemSetService.java
  Koco/src/main/java/icet/koco/problemSet/service/SurveyService.java
Labels: ✨feature, BE

#18 [Feat] 사용자 탈퇴 기능 구현 (#12)
  .idea/workspace.xml
  Koco/src/main/java/icet/koco/auth/controller/AuthController.java
  Koco/src/main/java/icet/koco/auth/service/AuthService.java
  Koco/src/main/java/icet/koco/auth/service/KakaoOAuthClient.java
  Koco/src/main/java/icet/koco/auth/service/LogoutService.java
  Koco/src/main/java/icet/koco/config/SecurityConfig.java
  Koco/src/main/java/icet/koco/config/WebClientConfig.java
  Koco/src/main/java/icet/koco/problemSet/controller/SurveyController.java
  Koco/src/main/java/icet/koco/problemSet/service/ProblemSetService.java
  Koco/src/main/java/icet/koco/problemSet/service/SurveyService.java
  Koco/src/main/java/icet/koco/user/controller/UserController.java
  Koco/src/main/java/icet/koco/user/repository/UserRepository.java
  Koco/src/main/java/icet/koco/user/service/UserService.java
  Koco/src/main/java/icet/koco/util/CookieUtil.java
  Koco/src/main/java/icet/koco/util/TokenExtractor.java
Labels: ✨feature, BE

#19 [Feat] 사용자 추가 정보 API 구현 (#11)
  .DS_Store
  .idea/dataSources.local.xml
  .idea/dataSources/b53a4fef-5b2d-4b59-9404-b62a8acb23ae.xml
  Koco/.DS_Store
  Koco/build.gradle
  Koco/src/.DS_Store
  Koco/src/main/.DS_Store
  Koco/src/main/java/.DS_Store
  Koco/src/main/java/icet/.DS_Store
  Koco/src/main/java/icet/koco/.DS_Store
  Koco/src/main/java/icet/koco/auth/controller/AuthController.java
  Koco/src/main/java/icet/koco/auth/dto/AuthResponse.java
  Koco/src/main/java/icet/koco/auth/service/KakaoOAuthClient.java
  Koco/src/main/java/icet/koco/config/S3Config.java
  Koco/src/main/java/icet/koco/config/SecurityConfig.java
  Koco/src/main/java/icet/koco/config/WebConfig.java
  Koco/src/main/java/icet/koco/problemSet/controller/ProblemSetController.java
  Koco/src/main/java/icet/koco/user/.DS_Store
  Koco/src/main/java/icet/koco/user/controller/UserController.java
  Koco/src/main/java/icet/koco/user/dto/UserResponse.java
  Koco/src/main/java/icet/koco/user/entity/User.java
  Koco/src/main/java/icet/koco/user/entity/UserDetail.java
  Koco/src/main/java/icet/koco/user/service/UserService.java
  Koco/src/main/java/icet/koco/user/service/uploader/ImageUploader.java
  Koco/src/main/java/icet/koco/user/service/uploader/LocalUploader.java
  Koco/src/main/java/icet/koco/user/service/uploader/S3Uploader.java
  Koco/src/main/resources/application.properties
Labels: ✨feature, BE

#20 [Feat] 문제 해설 조회 기능 API 구현 (#10)
  Koco/src/main/java/icet/koco/problemSet/controller/ProblemSetController.java
  Koco/src/main/java/icet/koco/problemSet/controller/SolutionController.java
  Koco/src/main/java/icet/koco/problemSet/dto/AiSolutionRequestDto.java
  Koco/src/main/java/icet/koco/problemSet/dto/ProblemSolutionResponseDto.java
  Koco/src/main/java/icet/koco/problemSet/repository/ProblemRepository.java
  Koco/src/main/java/icet/koco/problemSet/repository/SolutionRepository.java
  Koco/src/main/java/icet/koco/problemSet/service/ProblemSetService.java
  Koco/src/main/java/icet/koco/problemSet/service/SolutionService.java
Labels: ✨feature, BE

#21 [Feat] 유저 대시보드 API 구현 (#13)
  Koco/src/main/java/icet/koco/auth/controller/AuthController.java
  Koco/src/main/java/icet/koco/config/SecurityConfig.java
  Koco/src/main/java/icet/koco/global/exception/GlobalExceptionHandler.java
  Koco/src/main/java/icet/koco/problemSet/controller/ProblemSetController.java
  Koco/src/main/java/icet/koco/problemSet/controller/SolutionController.java
  Koco/src/main/java/icet/koco/problemSet/controller/SurveyController.java
  Koco/src/main/java/icet/koco/problemSet/entity/Survey.java
  Koco/src/main/java/icet/koco/problemSet/repository/SurveyRepository.java
  Koco/src/main/java/icet/koco/problemSet/repository/SurveyRepositoryCustom.java
  Koco/src/main/java/icet/koco/problemSet/repository/impl/SurveyRepositoryImpl.java
  Koco/src/main/java/icet/koco/user/controller/UserController.java
  Koco/src/main/java/icet/koco/user/dto/DashboardResponseDto.java
  Koco/src/main/java/icet/koco/user/dto/UserCategoryStatDto.java
  Koco/src/main/java/icet/koco/user/dto/UserCategoryStatProjection.java
  Koco/src/main/java/icet/koco/user/entity/UserAlgorithmStats.java
  Koco/src/main/java/icet/koco/user/entity/UserDetail.java
  Koco/src/main/java/icet/koco/user/repository/UserAlgorithmStatsRepository.java
  Koco/src/main/java/icet/koco/user/repository/UserRepository.java
  Koco/src/main/java/icet/koco/user/service/UserAlgorithmStatsService.java
  Koco/src/main/java/icet/koco/user/service/UserService.java
  Koco/src/main/resources/application.properties
Labels: ✨feature, BE

#27 [Fix] Kakao Oauth nickname null값 해결 (#26)
  Koco/src/main/java/icet/koco/auth/dto/KakaoUserResponse.java
  Koco/src/main/java/icet/koco/auth/service/AuthService.java
Labels: 🐞bug, BE

#32 [Chore] 401 에러 추가 (#31)
  Koco/src/main/java/icet/koco/auth/controller/AuthController.java
Labels: 🧹chore, BE

#33 [Enhancement] 대시보드 조회 API 분리 (#30)
  .gitignore
  Koco/src/main/java/icet/koco/problemSet/dto/ProblemDto.java
  Koco/src/main/java/icet/koco/problemSet/dto/ProblemSolutionResponseDto.java
  Koco/src/main/java/icet/koco/problemSet/service/ProblemSetService.java
  Koco/src/main/java/icet/koco/user/controller/UserController.java
  Koco/src/main/java/icet/koco/user/dto/UserAlgorithmStatsResponseDto.java
  Koco/src/main/java/icet/koco/user/dto/UserInfoResponseDto.java
  Koco/src/main/java/icet/koco/user/service/UserService.java
Labels: 🔧enhancement, BE

#36 [Fix] 토큰 만료 시 401 에러 반환 (#35)
  Koco/src/main/java/icet/koco/util/JwtAuthenticationFilter.java
  Koco/src/main/java/icet/koco/util/JwtTokenProvider.java
Labels: 🐞bug, BE

#38 [Feat] 알고리즘 통계 계산 로직 변경 (#34)
  Koco/src/main/java/icet/koco/problemSet/controller/SurveyController.java
  Koco/src/main/java/icet/koco/problemSet/repository/SurveyRepository.java
  Koco/src/main/java/icet/koco/problemSet/service/SurveyService.java
  Koco/src/main/java/icet/koco/user/dto/UserAlgorithmStatsResponseDto.java
  Koco/src/main/java/icet/koco/user/dto/UserCategoryStatDto.java
  Koco/src/main/java/icet/koco/user/dto/UserCategoryStatProjection.java
  Koco/src/main/java/icet/koco/user/repository/UserAlgorithmStatsRepository.java
  Koco/src/main/java/icet/koco/user/service/UserAlgorithmStatsService.java
  Koco/src/main/java/icet/koco/user/service/UserService.java
Labels: ✨feature, 🔧enhancement, BE

#43 [Feat] API 문서 자동화 (#39)
  Koco/build.gradle
  Koco/src/main/java/icet/koco/KocoApplication.java
  Koco/src/main/java/icet/koco/auth/controller/AuthController.java
  Koco/src/main/java/icet/koco/auth/service/AuthService.java
  Koco/src/main/java/icet/koco/config/SecurityConfig.java
  Koco/src/main/java/icet/koco/config/SwaggerConfig.java
  Koco/src/main/java/icet/koco/problemSet/controller/ProblemSetController.java
  Koco/src/main/java/icet/koco/problemSet/controller/SolutionController.java
  Koco/src/main/java/icet/koco/problemSet/controller/SurveyController.java
  Koco/src/main/java/icet/koco/user/controller/UserController.java
  Koco/src/main/java/icet/koco/user/service/UserService.java
  Koco/src/main/java/icet/koco/util/TokenExtractor.java
Labels: 📚documentation, BE

#47 Feat: 백엔드 서버에 오류 로그 발생 시 디스코드 알람 전송하는 기능 추가 (#44)
  Koco/build.gradle
  Koco/src/main/resources/application.yml
  Koco/src/main/resources/console-appender.xml
  Koco/src/main/resources/discord-error-appender.xml
  Koco/src/main/resources/logback-spring.xml
Labels: ✨feature, BE

#49 [Chore] 로컬에서 작업 시 디스코드 알람 가지 않는 기능 수정 (#44)
  Koco/build.gradle
  Koco/src/main/resources/apllication-prod.yml
  Koco/src/main/resources/application-local.yml
  Koco/src/main/resources/application.yml
  Koco/src/main/resources/logback-spring.xml
Labels: 🧹chore, BE

#52 [Fix] Presigned URL로 AWS S3에 파일 업로드 (#48)
  Koco/build.gradle
  Koco/src/main/java/icet/koco/config/S3Config.java
  Koco/src/main/java/icet/koco/user/controller/UserController.java
  Koco/src/main/java/icet/koco/user/service/UserService.java
  Koco/src/main/java/icet/koco/user/service/uploader/ImageUploader.java
  Koco/src/main/java/icet/koco/user/service/uploader/LocalUploader.java
  Koco/src/main/java/icet/koco/user/service/uploader/S3Uploader.java
  Koco/src/main/java/icet/koco/util/uploader/S3PresignedUrlService.java
  Koco/src/main/java/icet/koco/util/uploader/S3UploadController.java
  Koco/src/main/java/icet/koco/util/uploader/dto/S3UrlResponseDto.java
  README.md
Labels: 🐞bug, 🔧enhancement, BE

#53 [Chore] Health Check API (#51)
  Koco/build.gradle
  Koco/src/main/java/icet/koco/config/SecurityConfig.java
Labels: 🧹chore, BE

#70 [Enhancement] 사용하지 않는 dead code 및 주석 정리 (#62)
  Koco/src/main/java/icet/koco/auth/controller/AuthController.java
  Koco/src/main/java/icet/koco/auth/dto/AuthResponse.java
  Koco/src/main/java/icet/koco/auth/dto/KakaoCallbackRequest.java
  Koco/src/main/java/icet/koco/auth/dto/KakaoUserResponse.java
  Koco/src/main/java/icet/koco/auth/dto/RefreshRequest.java
  Koco/src/main/java/icet/koco/auth/repository/OAuthRepository.java
  Koco/src/main/java/icet/koco/auth/service/AuthService.java
  Koco/src/main/java/icet/koco/auth/service/LogoutService.java
  Koco/src/main/java/icet/koco/config/WebConfig.java
  Koco/src/main/java/icet/koco/problemSet/controller/ProblemSetController.java
  Koco/src/main/java/icet/koco/problemSet/controller/SolutionController.java
  Koco/src/main/java/icet/koco/problemSet/controller/SurveyController.java
  Koco/src/main/java/icet/koco/problemSet/repository/SurveyRepository.java
  Koco/src/main/java/icet/koco/problemSet/repository/SurveyRepositoryCustom.java
  Koco/src/main/java/icet/koco/problemSet/repository/impl/SurveyRepositoryImpl.java
  Koco/src/main/java/icet/koco/problemSet/service/SolutionService.java
  Koco/src/main/java/icet/koco/problemSet/service/SurveyService.java
  Koco/src/main/java/icet/koco/user/repository/UserDetailRepository.java
  Koco/src/main/java/icet/koco/user/service/UserAlgorithmStatsService.java
  Koco/src/main/java/icet/koco/util/JwtAuthenticationFilter.java
  Koco/src/main/java/icet/koco/util/JwtTokenProvider.java
  Koco/src/main/java/icet/koco/util/s3uploader/S3PresignedUrlService.java
  Koco/src/main/java/icet/koco/util/s3uploader/S3UploadController.java
  Koco/src/main/java/icet/koco/util/s3uploader/dto/S3UrlResponseDto.java
  Koco/src/main/resources/application.properties
Labels: 🔧enhancement, 🧹chore, BE

#73 [Chore]JWT 필터 개선 및 부하테스트용 Access/Refresh Token 발급 (#71)
  Koco/src/main/java/icet/koco/auth/controller/AuthController.java
  Koco/src/main/java/icet/koco/auth/service/AuthService.java
  Koco/src/main/java/icet/koco/util/JwtAuthenticationFilter.java
  Koco/src/main/java/icet/koco/util/test/TestJwtGenerator.java
  Koco/src/main/resources/application.properties
Labels: 🧹chore, BE

#74 [Chore] 응답 처리 및 예외 처리 통일 (#63)
  Koco/src/main/java/icet/koco/auth/controller/AuthController.java
  Koco/src/main/java/icet/koco/auth/repository/OAuthRepository.java
  Koco/src/main/java/icet/koco/auth/service/AuthService.java
  Koco/src/main/java/icet/koco/enums/ApiResponseCode.java
  Koco/src/main/java/icet/koco/global/dto/ApiResponse.java
  Koco/src/main/java/icet/koco/global/dto/ErrorResponse.java
  Koco/src/main/java/icet/koco/global/exception/GlobalExceptionHandler.java
  Koco/src/main/java/icet/koco/problemSet/controller/ProblemSetController.java
  Koco/src/main/java/icet/koco/problemSet/controller/SolutionController.java
  Koco/src/main/java/icet/koco/problemSet/controller/SurveyController.java
  Koco/src/main/java/icet/koco/problemSet/service/SurveyService.java
  Koco/src/main/java/icet/koco/user/controller/UserController.java
  Koco/src/main/java/icet/koco/user/service/UserService.java
  Koco/src/main/java/icet/koco/util/s3uploader/S3UploadController.java
Labels: 🧹chore, BE
